name: Upload S3 CI/CD

on:
  push:
    branches:
      - main
    paths:
      - "services/lambda/upload**"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install Dependencies
        run: |
          cd services/lambda/upload
          yarn install --frozen-lockfile

      - name: Build Lambda Function
        run: |
          cd services/lambda/upload
          yarn build

      - name: Create Lambda Function Archive
        run: |
          cd services/lambda/upload
          zip -r lambda.zip .

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Update Lambda Function
        env:
          AWS_REGION: ${{ vars.AWS_REGION }}
          LAMBDA_FUNCTION_NAME: ${{ vars.UPLOAD_LAMBDA_FUNCTION_NAME }}
        run: |
          aws lambda update-function-code \
            --function-name $LAMBDA_FUNCTION_NAME \
            --zip-file fileb://services/lambda/upload/lambda.zip \
            --region $AWS_REGION
